"""baseline: current production schema

Revision ID: 8fcb87470f2e
Revises: 
Create Date: 2026-09-03 07:52:46.629216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcb87470f2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_equity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_equity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_equity_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_equity_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=20), server_default='KR_STOCK', nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)

    op.create_table('scan_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=True),
    sa.Column('signals_found', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_logs_id'), ['id'], unique=False)

    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_time', sa.DateTime(), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('signal_type', sa.String(length=20), nullable=True),
    sa.Column('stage', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('ma150', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('volume_avg', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('signal_date', sa.String(length=10), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('pivot_price', sa.Float(), nullable=True),
    sa.Column('support_level', sa.Float(), nullable=True),
    sa.Column('market_condition', sa.String(length=20), nullable=True),
    sa.Column('signal_quality', sa.String(length=10), nullable=True),
    sa.Column('rs_value', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('base_start_date', sa.String(length=10), nullable=True),
    sa.Column('base_end_date', sa.String(length=10), nullable=True),
    sa.Column('tight_start_date', sa.String(length=10), nullable=True),
    sa.Column('base_high', sa.Float(), nullable=True),
    sa.Column('base_low', sa.Float(), nullable=True),
    sa.Column('tight_high', sa.Float(), nullable=True),
    sa.Column('tight_low', sa.Float(), nullable=True),
    sa.Column('base_width_pct', sa.Float(), nullable=True),
    sa.Column('tight_width_pct', sa.Float(), nullable=True),
    sa.Column('contraction_ratio', sa.Float(), nullable=True),
    sa.Column('base_mode', sa.String(length=5), nullable=True),
    sa.Column('pivot_ext_pct', sa.Float(), nullable=True),
    sa.Column('upthrust_failed', sa.Boolean(), nullable=True),
    sa.Column('cur_ext_pct', sa.Float(), nullable=True),
    sa.Column('cur_stop_pct', sa.Float(), nullable=True),
    sa.Column('entry_warnings', sa.Text(), nullable=True),
    sa.Column('suggested_qty', sa.Integer(), nullable=True),
    sa.Column('r_per_share', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('position_pct', sa.Float(), nullable=True),
    sa.Column('sizing_constrained_by', sa.String(length=20), nullable=True),
    sa.Column('equity_snapshot', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('sector_name', sa.String(length=50), nullable=True),
    sa.Column('sector_stage', sa.String(length=10), nullable=True),
    sa.Column('rs_trend', sa.String(length=10), nullable=True),
    sa.Column('rs_zero_crossed', sa.Boolean(), nullable=True),
    sa.Column('strict_filter_passed', sa.Boolean(), nullable=True),
    sa.Column('filter_reasons', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_results_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_results_scan_time'), ['scan_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_results_strict_filter_passed'), ['strict_filter_passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_results_ticker'), ['ticker'], unique=False)

    op.create_table('upthrust_cooldowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('source_signal_date', sa.String(length=10), nullable=False),
    sa.Column('failed_date', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upthrust_cooldowns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upthrust_cooldowns_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upthrust_cooldowns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upthrust_cooldowns_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_upthrust_cooldowns_ticker'), ['ticker'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_ticker'), ['ticker'], unique=True)

    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('initial_stop_loss', sa.Float(), nullable=True),
    sa.Column('current_stop_loss', sa.Float(), nullable=True),
    sa.Column('initial_r', sa.Float(), nullable=True),
    sa.Column('sell_status', sa.String(length=20), server_default='PENDING', nullable=True),
    sa.Column('sell_severity', sa.String(length=10), nullable=True),
    sa.Column('sell_reason', sa.Text(), nullable=True),
    sa.Column('sell_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_alert_severity', sa.String(length=10), nullable=True),
    sa.Column('last_alert_reason', sa.String(length=200), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_ticker'), ['ticker'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_ticker'))
        batch_op.drop_index(batch_op.f('ix_holdings_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_ticker'))
        batch_op.drop_index(batch_op.f('ix_watchlist_id'))

    op.drop_table('watchlist')
    with op.batch_alter_table('upthrust_cooldowns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upthrust_cooldowns_ticker'))
        batch_op.drop_index(batch_op.f('ix_upthrust_cooldowns_market'))
        batch_op.drop_index(batch_op.f('ix_upthrust_cooldowns_id'))
        batch_op.drop_index(batch_op.f('ix_upthrust_cooldowns_expires_at'))

    op.drop_table('upthrust_cooldowns')
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_results_ticker'))
        batch_op.drop_index(batch_op.f('ix_scan_results_strict_filter_passed'))
        batch_op.drop_index(batch_op.f('ix_scan_results_scan_time'))
        batch_op.drop_index(batch_op.f('ix_scan_results_market'))
        batch_op.drop_index(batch_op.f('ix_scan_results_id'))

    op.drop_table('scan_results')
    with op.batch_alter_table('scan_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_logs_id'))

    op.drop_table('scan_logs')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('account_equity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_equity_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_account_equity_market'))

    op.drop_table('account_equity')
    # ### end Alembic commands ###
